### ISSUE TITLE
Update on Maven Central

### ISSUE THREAD

**Issue by Krigu** [simasch/qlrm#8]
The latest version of qlrm on Maven Central (1.6.1) does not yet include the null pointer fix for optional columns in the resultlist (50505917ca3024baee5e6d2ce0ad625fdb55319c). 

It would be great to have an updated version available.

**Comment by jitpack-io** [comment]
Hi 

Perhap's this will help you in the meantime: https://jitpack.io/#simasch/qlrm/5050591
JitPack can build qlrm at that commit and provide you with a maven dependency.

**Comment by simasch** [comment]
1.6.2 will be available in Maven central in the next few hours.

Sorry for the delay!
